language: java
matrix:
  include:
    - jdk: oraclejdk8

install:
  - gem install awesome_bot

script:
  - ./build.sh
  - awesome_bot README.md --allow-dupe --allow-redirect --allow 429 --skip-save-results
